#! /usr/bin/ruby

# Roll for Wondrous Items
# c.f. Dungeon Master's Guide, p. 247,249,251
#      Frostburn, p.109ff.
#      Sandstorm, p.131ff.


# extract random array element
class Array
  def random
    self.empty? ? nil : self.at(rand(self.size))
  end
end


ring = ["Ring of the Icy Soul (FRB)",
        "Ring of Floating (FRB)",
        "Ring of the White Wyrm (FRB)",
        "Ring of the Blazing Sun (SST)",
        "Ring of Sandform (SST)",
        "Ring of Sandstriding (SST)"]

rod = ["Icicle Rod (FRB)",
       "Rod of Piercing Cold (FRB)",
       "Rod of Sand Repelling (SST)"]

staff = ["Staff of the Iceberg (FRB)",
         "Staff of Winter (FRB)",
         "Staff of the Nomads (SST)",
         "Staff of the Pharaoh (SST)",
         "Staff of the Sands (SST)",
         "Staff of Withering Thirst (SST)"]

minor  = ["Quaal's Feather Token: Anchor (DMG)",
          "Universal Solvent (DMG)",
          "Elixir of Love (DMG)",
          "Unguent of Timelessness (DMG)",
          "Quaal's Feather Token: Fan (DMG)",
          "Dust if Tracelessness (DMG)",
          "Elixir of Hiding (DMG)",
          "Elixir of Sneaking (DMG)",
          "Elixir of Swimming (DMG)",
          "Elixir of Vision (DMG)",
          "Silversheen (DMG)",
          "Quaal's Feather Token: Bird (DMG)",
          "Quaal's Feather Token: Tree (DMG)",
          "Quaal's Feather Token: Swan Boat (DMG)",
          "Elixir of Truth (DMG)",
          "Quaal's Feather Token: Whip (DMG)",
          "Dust of Dryness (DMG)",
          "Bag of Tricks: Gray (DMG)",
          "Hand of the Mage (DMG)",
          "Bracers of Armor +1 (DMG)",
          "Cloak of Resistance +1 (DMG)",
          "Pearl of Power: 1st level (DMG)",
          "Phylactery of Faithfulness (DMG)",
          "Salve of Slipperiness (DMG)",
          "Elixir of Fire Breath (DMG)",
          "Pipes of the Sewers (DMG)",
          "Dust of Illusion (DMG)",
          "Goggles of Minute Seeing (DMG)",
          "Brooch of Shielding (DMG)",
          "Necklace of Fireballs Type I (DMG)",
          "Dust of Appearance (DMG)",
          "Hat of Disguise (DMG)",
          "Pipes of Sounding (DMG)",
          "Quiver of Ehlonna (DMG)",
          "Amulet of Natural Armor +1 (DMG)",
          "Heward's Handy Haversack (DMG)",
          "Horn of Fog (DMG)",
          "Elemental Gem (DMG)",
          "Robe of Bones (DMG)",
          "Sovereign Glue (DMG)",
          "Bag of Holding Type I (DMG)",
          "Boots of Elvenkind (DMG)",
          "Boots of the Winterland (DMG)",
          "Candle of Truth (DMG)",
          "Cloak of Elvenkind (DMG)",
          "Eyes of the Eagle (DMG)",
          "Scarab: Golembane (DMG)",
          "Necklace of Fireballs Type II (DMG)",
          "Stone of Alarm (DMG)",
          "Bag of Tricks: Rust (DMG)",
          "Bead of Force (DMG)",
          "Chime of Opening (DMG)",
          "Horseshoes of Speed (DMG)",
          "Rope of Climbing (DMG)",
          "Dust of Disappearance (DMG)",
          "Lens of Detection (DMG)",
          "Vestment: Druid's (DMG)",
          "Figurine ",
          "Figurine of Wondrous Power: Silver Raven (DMG)",
          "Amulet of Health +2 (DMG)",
          "Bracers of Armor +2 (DMG)",
          "Cloak of Charisma +2 (DMG)",
          "Cloak of Resistance +2 (DMG)",
          "Gauntlets of Ogre Power (DMG)",
          "Gloves of Arrow Snaring (DMG)",
          "Gloves of Dexterity +2 (DMG)",
          "Headband of Intellect +2 (DMG)",
          "Ioun Stone: Clear Spindle (DMG)",
          "Keoghtom’s Ointment (DMG)",
          "Nolzur’s Marvelous Pigments (DMG)",
          "Pearl of Power, 2nd level (DMG)",
          "Periapt of Wisdom +2 (DMG)",
          "Stone Salve (DMG)",
          "Necklace of Fireballs Type III (DMG)",
          "Circlet of Persuasion (DMG)",
          "Slippers of Spider Climbing (DMG)",
          "Incense of Meditation (DMG)",
          "Bag of Holding Type II (DMG)",
          "Bracers of Archery, lesser (DMG)",
          "Ioun Stone: Dusty Rose Prism (DMG)",
          "Helm of Comprehend Languages and Read Magic (DMG)",
          "Vest of Escape (DMG)",
          "Eversmoking Bottle (DMG)",
          "Murlynd’s Spoon (DMG)",
          "Necklace of Fireballs Type IV (DMG)",
          "Boots of Striding and Springing (DMG)",
          "Wind Fan (DMG)",
          "Amulet of Mighty Fists +1 (DMG)",
          "Horseshoes of a Zephyr (DMG)",
          "Pipes of Haunting (DMG)",
          "Necklace of Fireballs Type V (DMG)",
          "Gloves of Swimming and Climbing (DMG)",
          "Bag of Tricks: Tan (DMG)",
          "Circlet of Blasting, minor (DMG)",
          "Horn of Goodness / Evil (DMG)",
          "Robe of Useful Items (DMG)",
          "Boat, folding (DMG)",
          "Cloak of the Manta Ray (DMG)",
          "Bottle of Air (DMG)",
          "Bag of Holding Type III (DMG)",
          "Periapt of Health (DMG)",
          "Vial of Icy Sheets (FRB)",
          "Ashworm Pellet (SST)",
          "Lamp of Stars (SST)",
          "Opal of Tunneling (SST)",
          "Portable Fountain (SST)",
          "Portable Shade (SST)",
          "Replenishing Skin (SST)",
          "Sand Painting: Mandala of Peace (SST)",
          "Sand Painting: Travelers' Oasis (SST)",
          "Sandals of the Shifting Sands (SST)",
          "Slashing Sand (SST)",
          "Thirsty Sand (SST)"]

medium = ["Boots of Levitation (DMG)",
          "Harp of Charming (DMG)",
          "Amulet of Natural Armor +2 (DMG)",
          "Golem Manual: Flesh (DMG)",
          "Hand of Glory (DMG)",
          "Ioun Stone: Deep Red Sphere (DMG)",
          "Ioun Stone: Incandescent Blue Sphere (DMG)",
          "Ioun Stone: Pale Blue Rhomboid (DMG)",
          "Ioun Stone: Pink and Green Sphere (DMG)",
          "Ioun Stone: Pink Rhomboid (DMG)",
          "Ioun Stone: Scarlet and Blue Sphere (DMG)",
          "Deck of Illusions (DMG)",
          "Necklace of Fireballs type VI (DMG)",
          "Candle of Invocation (DMG)",
          "Bracers of Armor +3 (DMG)",
          "Cloak of Resistance +3 (DMG)",
          "Decanter of Endless Water (DMG)",
          "Necklace of Adaptation (DMG)",
          "Pearl of Power, 3rd level (DMG)",
          "Talisman of the Sphere (DMG)",
          "Figurine of Wondrous Power: Serpentine Owl (DMG)",
          "Necklace of Fireballs type VII (DMG)",
          "Strand of Prayer Beads, Lesser (DMG)",
          "Bag of Holding Type IV (DMG)",
          "Figurine of Wondrous Power: Bronze Griffon (DMG)",
          "Figurine of Wondrous Power: Ebony Fly (DMG)",
          "Glove of Storing (DMG)",
          "Ioun Stone: Dark Blue Rhomboid (DMG)",
          "Stone Horse, Courser (DMG)",
          "Cape of the Mountebank (DMG)",
          "Phylactery of Undead Turning (DMG)",
          "Gauntlet of Rust (DMG)",
          "Boots of Speed (DMG)",
          "Goggles of Night (DMG)",
          "Golem Manual: Clay (DMG)",
          "Medallion of Thoughts (DMG)",
          "Pipes of Pain (DMG)",
          "Boccob’s Blessed Book (DMG)",
          "Belt, Monk’s (DMG)",
          "Gem of Brightness (DMG)",
          "Lyre of Building (DMG)",
          "Cloak of Arachnida (DMG)",
          "Stone Horse, Destrier (DMG)",
          "Belt of Dwarvenkind (DMG)",
          "Periapt of Wound Closure (DMG)",
          "Horn of the Tritons (DMG)",
          "Pearl of the Sirines (DMG)",
          "Figurine of Wondrous Power: Onyx Dog (DMG)",
          "Amulet of Health +4 (DMG)",
          "Belt of Giant Strength +4 (DMG)",
          "Boots, Winged (DMG)",
          "Bracers of Armor +4 (DMG)",
          "Cloak of Charisma +4 (DMG)",
          "Cloak of Resistance +4 (DMG)",
          "Gloves of Dexterity +4 (DMG)",
          "Headband of Intellect +4 (DMG)",
          "Pearl of power, 4th level (DMG)",
          "Periapt of Wisdom +4 (DMG)",
          "Scabbard of Keen Edges (DMG)",
          "Figurine of Wondrous Power: Golden Lions (DMG)",
          "Chime of Interruption (DMG)",
          "Broom of Flying (DMG)",
          "Figurine of Wondrous Power: Marble Elephant (DMG)",
          "Amulet of Natural Armor +3 (DMG)",
          "Ioun Stone: Iridescent Spindle (DMG)",
          "Bracelet of Friends (DMG)",
          "Carpet of Flying, 5 ft. by 5 ft. (DMG)",
          "Horn of Blasting (DMG)",
          "Ioun Stone: Pale Lavender Ellipsoid (DMG)",
          "Ioun Stone: Pearly White Spindle (DMG)",
          "Portable Hole (DMG)",
          "Stone of Good Luck (luckstone) (DMG)",
          "Figurine of Wondrous Power: Ivory Goats (DMG)",
          "Rope of Entanglement (DMG)",
          "Golem Manual: Stone (DMG)",
          "Mask of the Skull (DMG)",
          "Mattock of the Titans (DMG)",
          "Circlet of Blasting, Major (DMG)",
          "Amulet of Mighty Fists +2 (DMG)",
          "Cloak of Displacement, Minor (DMG)",
          "Helm of Underwater Action (DMG)",
          "Bracers of Archery, Greater (DMG)",
          "Bracers of Armor +5 (DMG)",
          "Cloak of Resistance +5 (DMG)",
          "Eyes of Doom (DMG)",
          "Pearl of Power, 5th level (DMG)",
          "Maul of the Titans (DMG)",
          "Strand of Prayer Beads (DMG)",
          "Cloak of the Bat (DMG)",
          "Iron Bands of Bilarro (DMG)",
          "Cube of Frost Resistance (DMG)",
          "Helm of Telepathy (DMG)",
          "Periapt of Proof against Poison (DMG)",
          "Robe of Scintillating Colors (DMG)",
          "Manual of Bodily Health +1 (DMG)",
          "Manual of Gainful Exercise +1 (DMG)",
          "Manual of Quickness in Action +1 (DMG)",
          "Tome of Clear Thought +1 (DMG)",
          "Tome of Leadership and Influence +1 (DMG)",
          "Tome of Understanding +1 (DMG)",
          "Gloves of the Uldra Savant (FRB)",
          "Iceheart, Minor (FRB)",
          "Instant Igloo (FRB)",
          "Mantle of Hidden Faith (FRB)",
          "Simulacrum Elixir (FRB)",
          "Bottle of Endless Sand (SST)",
          "Burnoose of 1001 Thorns (SST)",
          "Cloak of Garden Shade (SST)",
          "Cloak of Sandswimming (SST)",
          "Everfresh Bottle (SST)",
          "Figurine of Wondrous Power: Gold Beetle (SST)",
          "Figurine of Wondrous Power: Ivory Camel (SST)",
          "Glove of Choking Sands (SST)",
          "Glove of Sand Shaping (SST)",
          "Goggles of the Desert (SST)",
          "Personal Oasis (SST)",
          "Tovar's Instant Well (SST)",
          "Veil of Allure (SST)",
          "Waterskin of Deluge (SST)"]

major  = ["Dimensional Shackles (DMG)",
          "Figurine of Wondrous Power: Obsidian Steed (DMG)",
          "Drums of Panic (DMG)",
          "Ioun Stone: Orange (DMG)",
          "Ioun Stone: Pale Green Prism (DMG)",
          "Lantern of Revealing (DMG)",
          "Robe of Blending (DMG)",
          "Amulet of Natural Armor +4 (DMG)",
          "Amulet of Proof against Detection and Location (DMG)",
          "Carpet of Flying, 5 ft. by 10 ft. (DMG)",
          "Golem Manual: Iron (DMG)",
          "Amulet of Health +6 (DMG)",
          "Belt of Giant Strength +6 (DMG)",
          "Bracers of Armor +6 (DMG)",
          "Cloak of Charisma +6 (DMG)",
          "Gloves of Dexterity +6 (DMG)",
          "Headband of Intellect +6 (DMG)",
          "Ioun Stone: Vibrant Purple Prism (DMG)",
          "Pearl of power, 6th level (DMG)",
          "Periapt of Wisdom +6 (DMG)",
          "Scarab of Protection (DMG)",
          "Ioun Stone: Lavender and Green Ellipsoid (DMG)",
          "Ring Gates (DMG)",
          "Crystal Ball (DMG)",
          "Golem Manual: Greater Stone (DMG)",
          "Orb of Storms (DMG)",
          "Boots of Teleportation (DMG)",
          "Bracers of Armor +7 (DMG)",
          "Pearl of Power, 7th level (DMG)",
          "Amulet of Natural Armor +5 (DMG)",
          "Cloak of Displacement, Major (DMG)",
          "Crystal Ball with See Invisibility (DMG)",
          "Horn of Valhalla (DMG)",
          "Crystal Ball with Detect Thoughts (DMG)",
          "Carpet of flying, 6 ft. by 9 ft. (DMG)",
          "Amulet of Mighty Fists +3 (DMG)",
          "Wings of Flying (DMG)",
          "Cloak of Etherealness (DMG)",
          "Daern’s Instant Fortress (DMG)",
          "Manual of Bodily Health +2 (DMG)",
          "Manual of Gainful Exercise +2 (DMG)",
          "Manual of Quickness in Action +2 (DMG)",
          "Tome of Clear Thought +2 (DMG)",
          "Tome of Leadership and Influence +2 (DMG)",
          "Tome of Understanding +2 (DMG)",
          "Eyes of Charming (DMG)",
          "Robe of Stars (DMG)",
          "Carpet of Flying, 10 ft. by 10 ft. (DMG)",
          "Darkskull (DMG)",
          "Cube of Force (DMG)",
          "Bracers of Armor +8 (DMG)",
          "Pearl of Power, 8th level (DMG)",
          "Crystal Ball with Telepathy (DMG)",
          "Horn of Blasting, Greater (DMG)",
          "Pearl of Power, Two Spells (DMG)",
          "Helm of Teleportation (DMG)",
          "Gem of Seeing (DMG)",
          "Robe of the Archmagi (DMG)",
          "Mantle of Faith (DMG)",
          "Crystal Ball with True Seeing (DMG)",
          "Pearl of Power, 9th level (DMG)",
          "Well of Many Worlds (DMG)",
          "Manual of Bodily Health +3 (DMG)",
          "Manual of Gainful Exercise +3 (DMG)",
          "Manual of Quickness in Action +3 (DMG)",
          "Tome of Clear Thought +3 (DMG)",
          "Tome of Leadership and Influence +3 (DMG)",
          "Tome of Understanding +3 (DMG)",
          "Apparatus of Kwalish (DMG)",
          "Mantle of Spell Resistance (DMG)",
          "Mirror of Opposition (DMG)",
          "Strand of Prayer Beads, Greater (DMG)",
          "Amulet of Mighty Fists +4 (DMG)",
          "Eyes of Petrification (DMG)",
          "Bowl of Commanding Water Elementals (DMG)",
          "Brazier of Commanding Fire Elementals (DMG)",
          "Censer of Controlling Air Elementals (DMG)",
          "Stone of Controlling Earth Elementals (DMG)",
          "Manual of Bodily Health +4 (DMG)",
          "Manual of Gainful Exercise +4 (DMG)",
          "Manual of Quickness in Action +4 (DMG)",
          "Tome of Clear Thought +4 (DMG)",
          "Tome of Leadership and Influence +4 (DMG)",
          "Tome of Understanding +4 (DMG)",
          "Amulet of the Planes (DMG)",
          "Robe of Eyes (DMG)",
          "Helm of Brilliance (DMG)",
          "Manual of Bodily Health +5 (DMG)",
          "Manual of Gainful Exercise +5 (DMG)",
          "Manual of Quickness in Action +5 (DMG)",
          "Tome of Clear Thought +5 (DMG)",
          "Tome of Leadership and Influence +5 (DMG)",
          "Tome of Understanding +5 (DMG)",
          "Efreeti Bottle (DMG)",
          "Amulet of Mighty Fists +5 (DMG)",
          "Chaos Diamond (DMG)",
          "Cubic Gate (DMG)",
          "Iron Flask (DMG)",
          "Mirror of Mental Prowess (DMG)",
          "Mirror of Life Trapping (DMG)",
          "Frostfell Figurine of Wondrous Power: Basalt Glyptodon (FRB)",
          "Frostfell Figurine of Wondrous Power: Coral Zeuglodon (FRB)",
          "Frostfell Figurine of Wondrous Power: Diamond Ice Toad (FRB)",
          "Frostfell Figurine of Wondrous Power: Iron Megaloceros (FRB)",
          "Frostfell Figurine of Wondrous Power: Malachite Smilodon (FRB)",
          "Iceheart, Major (FRB)",
          "Burnoose of Moonless Nights (SST)",
          "Cape of the Wastes (SST)",
          "Folding Sand Vessel (SST)",
          "Glass of Distance (SST)",
          "Jug of Whirlwinds (SST)",
          "Lens of the Desert (SST)",
          "Mask of Sweet Air (SST)"]

artefact_minor = ["Book of Exalted Deeds (DMG)",
                  "Book of Infinite Spells (DMG)",
                  "Book of Vile Darkness (DMG)",
                  "Deck of Many Things (DMG)",
                  "Hammer of Thunderbolts (DMG)",
                  "Philosopher's Stone (DMG)",
                  "Sphere of Annihilation (DMG)",
                  "Staff of the Magi (DMG)",
                  "Talisman of Pure Good (DMG)",
                  "Talisman of the Sphere (DMG)",
                  "Talisman of Ultimate Evil (DMG)",
                  "Talisman of Zagy (DMG)",
                  "Crystal Tear (FRB)"]

artefact_major = ["The Hand and Eye of Vecna (DMG)",
                  "The Mace of Cuthbert (DMG)",
                  "The Moaning Diamond (DMG)",
                  "The Orbs of Dragonkind (DMG)",
                  "The Shadowstaff (DMG)",
                  "The Shield of Prator (DMG)",
                  "The Sword of Kas (DMG)"]


ARGV.each do
  |arg|
  next  unless arg =~ /^\d+$/
  arg = arg.to_i
  puts minor.random            if arg == 1
  puts medium.random           if arg == 2
  puts major.random            if arg == 3
  puts artefact_minor.random   if arg == 4
  puts artefact_major.random   if arg == 4
end
