% ******************** start of: char_arianna.inc
%


% ***************************************************** Riding Horse
dnl include(`char_arianna.anm')dnl

%
%
% ***************************************************** Items
\textbf{\underline{Armor, Weapons, Clothes:}} \\
Full Plate, Heavy Steel Shield

Longsword, Longbow plus 20 Arrows, Whetstone

%
% ***************************************************** Potions, etc.
\textbf{\underline{Potions, Oils, Scrolls, Wands, Wondrous Items:}} \\
--

%
% ***************************************************** Normal Items, etc.
\textbf{\underline{Normal Items:}} \\
Backpack (Waterskin, 2 Trail Rations, Flint \& Steel, Tinderbox, Heavy Bedroll)

%
% ***************************************************** Normal Items, etc.
\textbf{\underline{Gems:}} \\
--

%
% ***************************************************** Items for Horse
%\textbf{\underline{Items for Horse:}} \\
%Military Saddle, Barding (Chain Shirt, 50~lbs.)% AC +4, max AC-DEX +4, Check Penalty -2, light armor

%
% ***************************************************** Wealth
\begin{tabularx}{\textwidth}{|l|X|}
\multicolumn{2}{l}{\textbf{Wealth:}%
\hfill
Platinum \hspace*{1ex} $\stackrel{\mbox{\tiny 1:10}}{\longrightarrow}$ \hspace*{1ex}%
Gold     \hspace*{1ex} $\stackrel{\mbox{\tiny 1:10}}{\longrightarrow}$ \hspace*{1ex}%
Silver   \hspace*{1ex} $\stackrel{\mbox{\tiny 1:10}}{\longrightarrow}$ \hspace*{1ex}%
Copper   \hspace*{1cm}1 coin = 1/50 lbs. $\approx$ 9 g}\\
\hline
Platinum & wealth_platinum \\ \hline
Gold     & wealth_gold     \\ \hline
Silver   & wealth_silver   \\ \hline
Copper   & wealth_copper   \\ \hline
\end{tabularx}

%
% ******************** end of: char_arianna.inc
