% ******************** start of: char_hannah.inc
%
\newpage
%
%
% ***************************************************** Items
\textbf{\underline{Armor, Weapons, Clothes:}} \\
Breastplate +4 of Improved Slick (+10 Escape Artist) and Improved Shadow (+10 Hide),
Heavy Steel Shield +4,
Circlet of Minor Blasting (p. 252),
Ring of Protection +3,
Ring of Mind Shield (p. 232),
Periapt of Wisdom +4,
Cloak of Charisma +2

Shocking Battleaxe +3,
Silvered Battleaxe

High Boots, Winter clothing, Snow shoes

Wooden Holy Symbol

%
% ***************************************************** Potions, etc.
\textbf{\underline{Potions, Oils, Scrolls, Wands, Wondrous Items:}} \\
%
%Potion of ```XXX''',
Potion for Melee \\
Potion of Remove Fear (2) \\
Potion of Levitate \\
Potion of Undetectable Alignment \\
Potion of Protection From Cold \\
Potion of Circle Against Good \\
Potion of Barkskin +2 \\
Potion of Cure Serious Wounds (6) \\
Potion of Cure Moderate Wounds (6)

%
%Oil of ```XXX''',

%
%Scroll of ```XXX''',
Scroll of Alarm (3) \\
Scroll of Neutralize Poison (3) \\
Scroll of Endure Elements (3) \\
Scroll of Circle Against Law (4) \\
Scroll of Identify (3)

%
%Wand of ```XXX'''
Wand of Cat's Grace (16) \\
Wand of Hold Person (32)

Horse Shoes of Zephyr (p. 260) \\
Elixir of Truth (p. 256)

Pearl of Power (3rd) \\
Pearl of Power (4th)

%
% ***************************************************** Spell Components, etc.
\textbf{\underline{Spell Component Pouch:}} \\
%Cat Hairs                                   % Cat's Grace
Diamond Dust (5)                             % Restauration

%
% ***************************************************** Normal Items, etc.
\textbf{\underline{Normal Items:}} \\
Backpack, Waterskin, 2 Trail Rations, Flint \& Steel, Tinderbox, Heavy Bedroll\\
Healer's Kit, Frostbite salve, Antitoxin (2), Bottle o' Booze \\
Torches, Everburning Torch \\
Fishing Set, Small Tent, Poncho \\
Bag of Holding (Type II) \\
Bottle of Elven Liqueur \\
Writings in Abyssal

%
% ***************************************************** Gems, Art Objects
\textbf{\underline{Gems:}} \\
Alexandrit (600 gp) \\
Blue Sapphire (1500 gp) \\
White Opal (800 gp) \\

%
% ***************************************************** Wealth
\begin{tabularx}{\textwidth}{|l|X|}
\multicolumn{2}{l}{\textbf{Wealth:}%
\hfill
Platinum \hspace*{1ex} $\stackrel{\mbox{\tiny 1:10}}{\longrightarrow}$ \hspace*{1ex}%
Gold     \hspace*{1ex} $\stackrel{\mbox{\tiny 1:10}}{\longrightarrow}$ \hspace*{1ex}%
Silver   \hspace*{1ex} $\stackrel{\mbox{\tiny 1:10}}{\longrightarrow}$ \hspace*{1ex}%
Copper   \hspace*{1cm}1 coin = 1/50 lbs. $\approx$ 9 g}\\
\hline
Platinum & wealth_platinum \\ \hline
Gold     & wealth_gold     \\ \hline
Silver   & wealth_silver   \\ \hline
Copper   & wealth_copper   \\ \hline
\end{tabularx}

3500 gp borrowed to Marcus

%
\newpage
% ***************************************************** Group's Treasure
\textbf{\underline{Group's Treasure:}} \\
120 pp \\
160 gp \\
10000 sp (in Portable Hole)

Potion of Magic Fang

Aquamarin (400 gp) \\
Black Pearl (600 gp, 500 gp, 700 gp) \\
Black Star Sapphire (800 gp) \\
Citrin (50 gp) \\
Iolith (40 gp) \\
Malachit (13 gp, 12 gp) \\
Onyx (70 gp) \\
Silver Pearl (100 gp)

%
% ***************************************************** Add Contacts
\textbf{\underline{Group Members:}} \\
Gigglenot (Gnomish Rogue/Temple Raider, Thomas) \\
Xanora (Half-Elven Sorceress) \\
Ole (Uthgard Barbarian from Grey Wolf Clan)

\textbf{\underline{Three Oaks:}} \\
Urik Ringart (Dwarfen Warrior, Uwe) \\
Jigban Truestep (Falanghn Priest) \\
Marla Nimblefoot (Human Falanghn Cleric) \\
Marcus (Human Fighter) \\
Dr Zook (Gnomish Wizard)

\textbf{\underline{Not Quite Three Oaks:}} \\
Sirial (Air Elven Cleric) \\
Roscoe Leagallow (Halfling Rogue/Temple Raider) \\
Melokrates (Sartyr)

\textbf{\underline{Grey Wolf Clan:}} \\
Asrik (would be Sorcerer if he weren't Uthgard) \\
Tjuge (Ranger)

%
% ***************************************************** Add Spell Table
\newpage
%\vspace*{3ex}
include(`spells_definitions.m4')dnl

%
% ******************** end of: char_hannah.inc
