% ******************** start of file: char_liro.inc
%
\newpage
% ***************************************************** Items
\textbf{\underline{Armor, Weapons, Clothes:}} \\
Ring (unadorned, smooth, robust) of ```Protection +5'''\\
Nunchaku +2, shock, axiomatic (no lawful dam. red.)\\
Nunchaku +3 of frost\\
Nunchaku (vicious +1)\\
Kama +4 axiomatic vicious shocking burst\\
Ioun Stone (pale blue rhomboid) +2 strength\\
Cloak with Sign of Alysha\\
Monks Belt (AC+1)\\
Bracers of Armor +6\\
Gloves of Dexterity +4\\
Boots of Elvenkind (Move Silently +5)\\
Amulet of natural armor +2\\
Periapt of Wisdom +4\\
Cape of Mountebank (Dimension Door once per day)\\
Stone of Good Luck (+1 on skills and saves) 
%
% ***************************************************** Potions, etc.

\textbf{\underline{Potions, Oils, Scrolls, Wands, Wondrous Items:}} \\
%
Potion of ```Jump'''  \\ % from Hazela
Potion Shield of faith\\
Potion of cure light wounds\\
Potion of cure moderate wounds\\
Potion of cure light wounds\\
Potion of cure serious wounds \\
Potion of cure serious wounds
%
% ***************************************************** Normal Items, etc.

\textbf{\underline{Normal Items:}} \\
Clothing\\
Monks robes 2x\\
Desert set\\
Backpack\\
Waterskin 2x\\
Bedroll\\
Flint+Steel\\
Sack\\
Torches\\
Pouch\\
Hooded Lantern\\
Oil\\
Rope 5 yards\\
Sling Bullets 22x\\
Ring with dwarfen clan symbol\\
%
% ***************************************************** Wealth
\begin{tabularx}{\textwidth}{|l|X|}
\multicolumn{2}{l}{\textbf{Wealth:}%
\hfill
Platinum \hspace*{1ex} $\stackrel{\mbox{\tiny 1:10}}{\longrightarrow}$ \hspace*{1ex}%
Gold     \hspace*{1ex} $\stackrel{\mbox{\tiny 1:10}}{\longrightarrow}$ \hspace*{1ex}%
Silver   \hspace*{1ex} $\stackrel{\mbox{\tiny 1:10}}{\longrightarrow}$ \hspace*{1ex}%
Copper   \hspace*{1cm}1 coin = 1/50 lbs. $\approx$ 9 g}\\
\hline
Platinum & wealth_platinum \\ \hline
Gold     & wealth_gold     \\ \hline
Silver   & wealth_silver   \\ \hline
Copper   & wealth_copper   \\ \hline
\end{tabularx}
%
% ******************** end of file: char_liro.inc
